/*
LeetCode 389: Find the Difference

Problem Statement:
You are given two strings s and t.

String t is generated by randomly shuffling string s
and then adding one more letter.

Return the letter that was added.

Example:
Input:
s = "abcd"
t = "abcde"

Output:
e
*/

class Solution {
    public char findTheDifference(String s, String t) {
        char result = 0;

        for(char ch : s.toCharArray()) {
            result ^= ch;
        }

        for(char ch : t.toCharArray()) {
            result ^= ch;
        }

        return result;
    }
}

public class Main {
    public static void main(String[] args) {
        String s = "abcd";
        String t = "abcde";

        Solution obj = new Solution();
        System.out.println("Output: " + obj.findTheDifference(s, t));
    }
}